// src/data.js

export const projectsData = [
  {
    id: "Tracer_Study_Dashboard-Information_System_UIN_Jakarta",
    title: "Tracer Study Dashboard - Information System UIN Jakarta",
    description: "Designed a multi-page interactive dashboard using Looker Studio to visualize Tracer Study data of nearly 200 alumni, tracking employment rates, competency gaps, and career trajectories for data-driven academic evaluation.",
    image: "/portfolio/projects/TS HIMSI/Tracer_Study_Sistem_Informasi_2025.jpg", 
    embedUrl: "https://datastudio.google.com/embed/reporting/c1d0ea5a-8760-411e-bbc2-aa2890641b1e/page/iHGIF",
    reportPdf: "",
    techStack: ["Looker Studio", "Google Sheets"],
    datasetSource: "Internal Organizational Data",
    datasetLink: "",
    dashboardLink: "https://datastudio.google.com/reporting/c1d0ea5a-8760-411e-bbc2-aa2890641b1e", 
    reportLink: "",
    background: "The Information Systems Department of UIN Jakarta required a systematic approach to track and evaluate alumni career trajectories, academic relevance, and market competitiveness. This project aimed to transform raw Tracer Study survey data into an interactive, multi-page dashboard to provide university stakeholders with actionable insights for curriculum refinement and accreditation purposes.",
    dataPrep: "Aggregated internal survey responses from nearly 200 alumni. The data cleaning and preparation process in Google Sheets involved standardizing varied inputs, such as salary ranges, job position hierarchies, and company sectors, handling missing values, and structuring the relational dataset to ensure seamless and automated integration with Looker Studio.",
    eda: "Exploratory Data Analysis (EDA) revealed a strong baseline with an 84% employment rate, while 13% remained unemployed and 3% pursued further studies. The initial competency evaluation highlighted that alumni possessed excellent soft skills in Self-Development and Teamwork, but identified notable gaps in English Proficiency and Field-Specific Expertise when compared against current workplace demands.",
    analysis: "Conducted a multi-dimensional analysis across four distinct sectors: Career, Entrepreneurship, Further Study, and Unemployment. Key findings indicated that 49.5% of employed alumni secured their first job within 6 months of graduation, predominantly occupying Staff positions (78.7%) within National-scale companies. In the educational sector, internships (Magang) and practicums were rated as the most effective learning methods for professional readiness. The unemployment analysis isolated primary barriers, such as active application delays and overall job market difficulty.",
    insights: "The dashboard delivers critical data-driven directives for the Information Systems Department. It highlights the urgent need to close the competency gap by integrating more rigorous English and technical training into the curriculum. Additionally, the visibility into the 13% unemployment segment allows the study program to deploy targeted interventions, such as specialized bootcamps or job-matching programs, to accelerate alumni placement.",
  },
  {
    id: "Event_Satisfaction_Survey_Dashboard-HIMSI_UIN_Jakarta",
    title: "Event Satisfaction Survey Dashboard - HIMSI UIN Jakarta",
    description: "Developed an interactive Looker Studio dashboard to analyze feedback from over 1,100 participants across multiple events, translating quantitative ratings and qualitative text reviews into actionable organizational insights.",
    image: "/portfolio/projects/TS HIMSI/HIMSI_Satisfaction_Survey_Dashboard.jpg",
    embedUrl: "https://datastudio.google.com/embed/reporting/d217f4ce-feb7-48fd-a3cd-84451b926240/page/p_6rzywaphtd",
    reportPdf: "",
    techStack: ["Looker Studio", "Google Sheets"],
    datasetSource: "Internal Organizational Data",
    datasetLink: "",
    dashboardLink: "https://datastudio.google.com/reporting/d217f4ce-feb7-48fd-a3cd-84451b926240", 
    reportLink: "",
    background: "HIMSI UIN Jakarta organizes numerous events throughout the year, but lacked a centralized system to measure participant satisfaction and evaluate committee performance. This project aimed to consolidate feedback from multiple events into a single, interactive dashboard, providing the organization's leadership with a data-driven tool to assess event quality and identify areas for operational improvement.",
    dataPrep: "Compiled and cleaned survey data from 1,191 respondents spanning various events from late 2025 to mid-2026. The data preparation involved standardizing quantitative metrics (ratings 1-5) across four key indicators: Content Quality, Comfortability, Responsiveness, and Credibility. Additionally, qualitative feedback (open-text responses) was aggregated to allow for detailed sentiment and issue tracking.",
    eda: "Initial Exploratory Data Analysis (EDA) revealed a strong overall satisfaction score of 4.49 out of 5, supported by a healthy 67% response rate. A demographic breakdown showed that the class of 2025 formed the majority of the respondent base (63.1%). The highest-rated metric was 'Credibility' (4.6), indicating strong trust in the speakers and facilitators, while 'Comfortability' (4.43) scored the lowest, suggesting potential facility or logistical issues.",
    analysis: "The dashboard enables drill-down analysis by specific events and timeframes. The 'Mentoring with Expert' event achieved the highest satisfaction score (4.77), closely followed by 'HIMSI PERCUSSION' (4.74). By analyzing the qualitative data sections ('Technical Issues & Facility Feedback' and 'Participant Feedback Insights'), recurring themes were identified. For instance, while participants praised the committee's responsiveness and clear material delivery, consistent complaints emerged regarding time management ('ngaret', ending too late) and specific logistical issues (e.g., audio quality, transportation comfort).",
    insights: "The dashboard provides actionable directives for future HIMSI committees. While content quality and committee professionalism are strong suits, the organization must prioritize improving time management and technical logistics (specifically audio and venue comfort). The consolidated qualitative feedback serves as a direct evaluation tool, allowing future event divisions to proactively address past logistical bottlenecks and further elevate the participant experience.",
  },
  {
    id: "Tracer_Study_Report-FST_UIN_Jakarta",
    title: "Tracer Study Report - FST UIN Jakarta",
    description: "Authored a comprehensive Tracer Study report analyzing career trajectories, employment metrics, and competency evaluations of 358 Faculty of Science and Technology graduates.",
    image: "portfolio/projects/FST/FST.png",
    embedUrl: "/portfolio/projects/FST/PPT TS FST S10_.pdf",
    reportPdf: "/portfolio/projects/FST/REPORT FST TS-1.pdf",
    techStack: ["Looker Studio", "Google Sheets"],
    datasetSource: "Internal Organizational Data",
    datasetLink: "",
    dashboardLink: "/portfolio/projects/FST/PPT TS FST S10_.pdf", 
    reportLink: "/portfolio/projects/FST/REPORT FST TS-1.pdf",
    background: "As a Data Specialist Intern at the UIN Jakarta Career Center, I was tasked with orchestrating the 2026 Tracer Study for the Faculty of Science and Technology (FST). The objective was to evaluate the higher education outcomes of the 2025 graduating class, providing the faculty with a comprehensive data-driven report to assess graduate employability, curriculum relevance, and overall institutional quality.",
    dataPrep: "Managed and cleaned a complex dataset comprising 358 survey respondents across 9 distinct study programs, achieving a 50.92% response rate. A major challenge during data preparation was consolidating fragmented data caused by a mid-period transition between faculty-managed survey links and the centralized Career Center system. I successfully harmonized these datasets to prevent duplication and ensure reporting accuracy.",
    eda: "Exploratory Data Analysis (EDA) established a robust academic baseline, with 63.1% of graduates holding a GPA between 3.50-4.00. The demographic and activity breakdown revealed that 45% of the alumni were actively employed, 41.3% were seeking employment, 11.5% were managing their own businesses, and 2.2% were pursuing further studies (Magister/S2).",
    analysis: "Deep-dive analysis into the employed cohort demonstrated a fast absorption rate, with 92.8% securing jobs either before or within 6 months of graduation. The competency evaluation highlighted that Communication, Teamwork, and Information Technology were the most critical skills utilized in the workplace. For the entrepreneurial segment, the data showed a strong inclination toward micro-enterprises (70.8%), while unemployment data pointed to overall job market difficulty as the primary barrier.",
    insights: "The final report delivered strategic recommendations for FST's decanate. Given the 41.3% job-seeking rate, I recommended intensifying targeted career guidance and industry networking. Academically, the data strongly supported the optimization of experiential learning methods—such as practicums and internships—which alumni rated as highly effective, alongside a strategic review of the Arabic language curriculum to better align with current industrial demands.",
  },
  {
    id: "Program-Level_Tracer_Study_Report-FST_UIN_Jakarta",
    title: "Program-Level Tracer Study Report - FST UIN Jakarta",
    description: "Segmented and analyzed Tracer Study data across 9 distinct study programs, producing granular employability and competency reports tailored for departmental accreditations.",
    image: "portfolio/projects/FST/FST.png",
    embedUrl: "/portfolio/projects/FST/PRODI PPT TS FST S10_.pdf",
    reportPdf: "/portfolio/projects/FST/REPORT FST TS-1 PRODI_.pdf",
    techStack: ["Looker Studio", "Google Sheets"],
    datasetSource: "Internal Organizational Data",
    datasetLink: "",
    dashboardLink: "/portfolio/projects/FST/PRODI PPT TS FST S10_.pdf", 
    reportLink: "/portfolio/projects/FST/REPORT FST TS-1 PRODI_.pdf",
    background: "Following the faculty-wide Tracer Study evaluation, there was a critical need for granular, department-specific insights. Each of the 9 study programs within the Faculty of Science and Technology required tailored analytics on their respective graduates to fulfill specific national accreditation standards and drive localized curriculum improvements.",
    dataPrep: "Managed the segmentation of 358 survey respondents into 9 distinct datasets representing programs such as Information Systems, Biology, Agribusiness, and Informatics Engineering. The data preparation process required meticulous filtering and validation to ensure that isolated program data maintained its integrity, especially when handling edge cases caused by the mid-year transition of the data collection platform.",
    eda: "Conducted Exploratory Data Analysis (EDA) on a micro-level for each department. The isolated metrics revealed highly diverse program landscapes. For instance, the Agribusiness program demonstrated an outstanding 86.26% response rate, while the Information Systems and Informatics Engineering programs showcased exceptionally high immediate employment rates (over 75%).",
    analysis: "Executed deep-dive comparative analyses tailored to each of the 9 study programs. Evaluated program-specific KPIs, including the linearity of current jobs to the graduates' majors, salary distributions compared to regional minimum wages (UMR), and granular competency gap assessments. The analysis also measured the effectiveness of program-specific teaching methods, consistently identifying 'Practicums' and 'Internships' as the highest-rated learning models across science and technology disciplines.",
    insights: "Delivered 9 customized, data-driven reports directly actionable for each Head of Study Program (Kaprodi). The granular insights empowered department leaders to pinpoint exact competency weaknesses (e.g., the varying relevance of Arabic language skills across different technical roles) and provided concrete, empirical evidence to support their upcoming academic accreditation portfolios.",
  },
  {
    id: "Postgraduate_Tracer_Study_Report-SPs_UIN_Jakarta",
    title: "Postgraduate Tracer Study Report - SPs UIN Jakarta",
    description: "Authored an advanced analytical Tracer Study for the Graduate School (SPs), evaluating the career trajectories, academic alignment, and curriculum effectiveness of Master's and Doctoral alumni.",
    image: "portfolio/projects/SPS/FSPS.png",
    embedUrl: "/portfolio/projects/SPS/PPT TS SPS S10_.pdf",
    reportPdf: "/portfolio/projects/SPS/REPORT FSPS TS-1.pdf",
    techStack: ["Looker Studio", "Google Sheets"],
    datasetSource: "Internal Organizational Data",
    datasetLink: "",
    dashboardLink: "/portfolio/projects/SPS/PPT TS SPS S10_.pdf", 
    reportLink: "/portfolio/projects/SPS/REPORT FSPS TS-1.pdf",
    background: "The Graduate School (Sekolah Pascasarjana/SPs) of UIN Jakarta required a specialized Tracer Study to evaluate the outcomes of its advanced degree programs. Unlike undergraduate studies, this project aimed to analyze the career progression, research quality, and curriculum effectiveness for Master's and Doctoral alumni, providing executive insights for institutional quality assurance.",
    dataPrep: "Processed and analyzed survey data from 44 postgraduate respondents, comprising 47.7% Master's and 52.3% Doctoral alumni from the Islamic Studies program. The data preparation involved categorizing unique post-graduate employment statuses, specifically isolating the 'Kembali Bekerja' (Returning to Work) demographic, which is highly prevalent in advanced degree cohorts.",
    eda: "Exploratory Data Analysis revealed an exceptionally high academic performance baseline, with 93.2% of the graduates achieving a GPA between 3.50 and 4.00. The demographic split showed a strong male dominance at 77.3%, and the overall employment metrics indicated that 77.2% of the alumni were either actively working or had returned to their previous workplaces post-graduation.",
    analysis: "Deep-dive analysis into the professional sector highlighted a massive concentration in academia and education. A staggering 56.5% of the working alumni served as University Lecturers (Dosen) and 17.4% as Teachers (Guru). The institutional distribution analysis further mapped these alumni predominantly to State Islamic Universities (PTKIN), government research bodies like BRIN, and various educational foundations.",
    insights: "The report delivered highly positive feedback for the SPs curriculum, with 95.3% of alumni affirming that the coursework strongly supported their current professions. However, the qualitative data analysis uncovered administrative bottlenecks; while academic quality was praised, 34.9% of respondents noted that multilayered exam bureaucracies and verifications hindered on-time graduation. This provided the Dean's office with precise, actionable targets for administrative reform.",
  },
  {
    id: "Program-Level_Tracer_Study_Report-SPs_UIN_Jakarta",
    title: "Program-Level Tracer Study Report - SPs UIN Jakarta",
    description: "Segmented and analyzed Tracer Study data for Master's and Doctoral programs, delivering tailored analytics on postgraduate career trajectories and specific academic bottlenecks.",
    image: "portfolio/projects/SPS/FSPS.png",
    embedUrl: "/portfolio/projects/SPS/PRODI PPT TS SPS S10_.pdf",
    reportPdf: "/portfolio/projects/SPS/REPORT FSPS TS-1 PRODI.pdf",
    techStack: ["Looker Studio", "Google Sheets"],
    datasetSource: "Internal Organizational Data",
    datasetLink: "",
    dashboardLink: "/portfolio/projects/SPS/PRODI PPT TS SPS S10_.pdf",
    reportLink: "/portfolio/projects/SPS/REPORT FSPS TS-1 PRODI.pdf",
    background: "Following the macro-level evaluation of the Graduate School (SPs), there was a strategic need to dissect the data at the program level. This project focused on isolating the analytics for the Master's (S2) and Doctoral (S3) programs in Islamic Studies to provide department heads (Kaprodi) with granular insights into the unique career dynamics and specific academic challenges faced by their respective cohorts.",
    dataPrep: "Segmented the overarching postgraduate dataset into two distinct programmatic cohorts: Master's in Islamic Studies (21 respondents) and Doctorate in Islamic Studies (23 respondents). The data preparation phase required meticulous handling of advanced employment categories, specifically isolating and validating the 'Kembali Bekerja' (Returning to Work) demographic, which behaves fundamentally differently from fresh graduates seeking new employment.",
    eda: "Exploratory Data Analysis (EDA) at the micro-level revealed fascinating programmatic distinctions. The Master's cohort demonstrated a flawless academic baseline, with 100% of graduates achieving a GPA between 3.50 and 4.00. Activity metrics highlighted varying career motivations: while 38.1% of Master's graduates returned to their previous employers, a much more dominant 65.2% of Doctoral graduates did so, indicating that the S3 degree is primarily utilized for career consolidation and rank elevation.",
    analysis: "Executed comparative deep dives into the professional sectors of both programs. The analysis confirmed that alumni returning to work predominantly served as University Lecturers (Dosen) at State Islamic Universities (PTKIN) and researchers at government bodies like BRIN. Pedagogically, the data showed that 'Discussion' was the most heavily emphasized and appreciated learning method across both S2 and S3, which aligns perfectly with the critical-thinking requirements of advanced Islamic Studies.",
    insights: "Delivered customized, data-driven reports directly to the department heads. A critical, actionable insight uncovered during this granular analysis was the qualitative feedback regarding the layered examination bureaucracy (e.g., Proposal, WIP, and Comprehensive exams). While the curriculum itself was highly praised, 45% of Doctoral respondents cited these administrative bottlenecks as the primary hurdle to on-time graduation, empowering the faculty to streamline procedures without sacrificing academic rigor.",
  }
];

export const certificatesData = [
  {
    id: "Certificate_Hitlab",
    title: "Data Analyst Tech Class",
    issuer: "HITLAB HI-NECT UIN Jakarta",
    image: ["/portfolio/certif/Hitlab_page-0001.jpg", "/portfolio/certif/Hitlab_page-0002.jpg", "/portfolio/certif/Hitlab_page-0003.jpg"]
  },
  {
    id: "Certificate_Kelas_Bagus",
    title: "Kelas Bagus Batch#2",
    issuer: "Kelas Bagus",
    image: ["/portfolio/certif/Kelas bagus.png"]
  },
  {
    id: "Certificate_Data_Science",
    title: "Belajar Dasar Data Science",
    issuer: "Dicoding",
    image: ["/portfolio/certif/DS-Dicoding-1.jpg","/portfolio/certif/DS-Dicoding-2.jpg", "/portfolio/certif/DS-Dicoding-3.jpg", "/portfolio/certif/DS-Dicoding-4.jpg"]
  },
  {
    id: "Certificate_SQL",
    title: "Belajar Dasar SQL",
    issuer: "Dicoding",
    image: ["/portfolio/certif/SQL-Dicoding-1.jpg","/portfolio/certif/SQL-Dicoding-2.jpg", "/portfolio/certif/SQL-Dicoding-3.jpg"]
  },
  {
    id: "Certificate_Data_Analytics",
    title: "Data Analytics Essentials",
    issuer: "Cisco Networking Academy",
    image: ["/portfolio/certif/cisco-gdkb.jpg"]
  },
  {
    id: "Certificate_Financial_Literacy",
    title: "Introduction to Financial Literacy",
    issuer: "Dicoding",
    image: ["/portfolio/certif/Financial-Dicoding-1.jpg","/portfolio/certif/Financial-Dicoding-2.jpg", "/portfolio/certif/Financial-Dicoding-3.jpg"]
  }
];

